/* eslint-disable @typescript-eslint/no-unused-vars */
//const game = undefined;
//const CONFIG = undefined;
//const Actor = undefined;
//const Item = undefined;
const canvas = undefined;
const Folder = undefined;
const SortingHelpers = undefined;
const Combatant = undefined;
const ActiveEffect = undefined;
const Handlebars = undefined;
const foundry = undefined;
const CONST = undefined;
const Hooks = undefined;
const Journal = undefined;
const Macro = undefined;
const ChatMessage = undefined;
const Roll = undefined;
const $ = undefined;
const ui = undefined;
const Settings = undefined;
const FormApplication = undefined;
const ActiveEffectConfig = undefined;
const Tabs = undefined;
const saveDataToFile = undefined;
const FilePicker = undefined;
const Combat = undefined;
const TokenDocument = undefined;
const Dialog = undefined;
const Compendium = undefined;
async function fromUuid(id) { return undefined; }
function fromUuidSync(id) { return undefined; }