# EXAMPLE:
# git tag 0.7.12
# git push origin main
# git push origin 0.7.12
name: Build and Release Foundry VTT Module

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Generate release notes
        id: release_notes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
          NEW_TAG=${GITHUB_REF#refs/tags/}

          echo "**Full Changelog**: https://github.com/Forelius/fade-compendiums/compare/${LAST_TAG}...${NEW_TAG}" > release_notes.md
          echo "" >> release_notes.md
          echo "**Changes:**" >> release_notes.md
          
          git log ${LAST_TAG}..HEAD --pretty=format:"%B" --first-parent | grep '^-' >> release_notes.md

      - name: Prepare release zip
        run: |
          zip -r fade-compendiums.zip ./* -x '.git*' -x '.github/*'

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: fade-compendiums.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: release_notes.md
